/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saasms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author adisa
 */
public class DirectorofServices extends javax.swing.JFrame {

    /**
     * Creates new form DirectorofServices
     */
    public DirectorofServices() {
        initComponents();
        loadDashboardStats();
        loadAllStaff();
        loadUnitsToComboBox();
        populateRosterUnitComboBox();
        loadRosterData();

        filterText.setVisible(false);
        filterDate.setVisible(false);
        rosterUnitComboBox.setVisible(false);

        jTabbedPane1.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                int selectedIndex = jTabbedPane1.getSelectedIndex();
                if (selectedIndex == 1) { // Replace STAFF_TAB_INDEX with the correct index number
                    loadAllStaff();
                    loadUnits();
                    searchStaff();
                    loadRosterData();
                }
            }
        });

        filterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String selected = (String) filterCombo.getSelectedItem();

                // Hide all first
                filterText.setVisible(false);
                filterDate.setVisible(false);
                rosterUnitComboBox.setVisible(false);

                // Show only the relevant one
                if ("Staff ID".equals(selected)) {
                    filterText.setVisible(true);
                } else if ("Date".equals(selected)) {
                    filterDate.setVisible(true);
                } else if ("Unit".equals(selected)) {
                    rosterUnitComboBox.setVisible(true);
                }

                // Refresh layout
                filterText.getParent().revalidate();
                filterText.getParent().repaint();
            }
        });
        loadAttendanceLogs();           // Loads all logs
        populateUnitsCombo();           // Loads unique unit names

        logFilterText.setVisible(false);
        logFilterDate.setVisible(false);
        logUnitComboBox.setVisible(false);

        logFilterCombo.setModel(new DefaultComboBoxModel<>(new String[]{"All", "By Staff ID", "By Date", "By Unit"}));

        logFilterCombo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selected = (String) logFilterCombo.getSelectedItem();
                logFilterText.setVisible("By Staff ID".equals(selected));
                logFilterDate.setVisible("By Date".equals(selected));
                logUnitComboBox.setVisible("By Unit".equals(selected));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTotalStaffText = new javax.swing.JLabel();
        jLabelTotalStaff = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTotalUnits = new javax.swing.JLabel();
        jLabelTotalUnitsText = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelAttendanceRate = new javax.swing.JLabel();
        jLabelAttendanceRateText = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabelShiftSwaps = new javax.swing.JLabel();
        jLabelShiftSwapsText = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        filterButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        unitComboBox = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableRosters = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        filterDate = new com.toedter.calendar.JDateChooser();
        filterCombo = new javax.swing.JComboBox<>();
        btnApplyFilter = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        filterText = new javax.swing.JTextField();
        rosterUnitComboBox = new javax.swing.JComboBox<>();
        btnRefresh1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnApplyLogFilter = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        logsTable = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        logFilterDate = new com.toedter.calendar.JDateChooser();
        logFilterCombo = new javax.swing.JComboBox<>();
        logFilterText = new javax.swing.JTextField();
        logUnitComboBox = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(30, 30, 47));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jPanel1.setBackground(new java.awt.Color(74, 144, 226));
        jPanel1.setLayout(null);

        jLabelTotalStaffText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotalStaffText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalStaffText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalStaffText.setText("Total Staff");
        jPanel1.add(jLabelTotalStaffText);
        jLabelTotalStaffText.setBounds(0, 190, 430, 50);

        jLabelTotalStaff.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelTotalStaff.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalStaff.setText("numstaff");
        jPanel1.add(jLabelTotalStaff);
        jLabelTotalStaff.setBounds(10, 40, 430, 100);

        jPanel4.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(80, 227, 194));

        jLabelTotalUnits.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelTotalUnits.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalUnits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalUnits.setText("numunit");

        jLabelTotalUnitsText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotalUnitsText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalUnitsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalUnitsText.setText("Total Units");

        jButton19.setBackground(new java.awt.Color(255, 0, 0));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Log out");
        jButton19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton19.setBorderPainted(false);
        jButton19.setFocusPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTotalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabelTotalUnitsText, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton19)
                .addGap(38, 38, 38)
                .addComponent(jLabelTotalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelTotalUnitsText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(145, 181, 224));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabelAttendanceRate.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelAttendanceRate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAttendanceRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAttendanceRate.setText("%attendance");

        jLabelAttendanceRateText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAttendanceRateText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAttendanceRateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAttendanceRateText.setText("Attendance Rate");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAttendanceRateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAttendanceRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabelAttendanceRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAttendanceRateText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel3);

        jPanel9.setBackground(new java.awt.Color(242, 153, 74));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabelShiftSwaps.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabelShiftSwaps.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShiftSwaps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelShiftSwaps.setText("shiftswaps");

        jLabelShiftSwapsText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelShiftSwapsText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShiftSwapsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelShiftSwapsText.setText("Shift Swaps This Week");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabelShiftSwaps, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelShiftSwapsText, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabelShiftSwaps, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelShiftSwapsText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel9);

        jTabbedPane1.addTab("Overview", null, jPanel4, "");

        jPanel8.setBackground(new java.awt.Color(30, 30, 47));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Staff Management");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Staff Name");

        searchTextField.setBackground(new java.awt.Color(42, 42, 64));
        searchTextField.setForeground(new java.awt.Color(220, 220, 220));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(74, 144, 226));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Find Staff");
        jButton20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton20.setBorderPainted(false);
        jButton20.setFocusPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        filterButton.setBackground(new java.awt.Color(74, 144, 226));
        filterButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        filterButton.setForeground(new java.awt.Color(255, 255, 255));
        filterButton.setText("Filter");
        filterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        filterButton.setBorderPainted(false);
        filterButton.setFocusPainted(false);
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        jScrollPane10.setBorder(null);
        jScrollPane10.setToolTipText("");

        jTable5.setBackground(new java.awt.Color(255, 255, 255));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " ID", "name", "email", "gender", "unit", "role", "phone_number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setShowGrid(true);
        jScrollPane10.setViewportView(jTable5);

        jScrollPane9.setViewportView(jScrollPane10);

        jButton22.setBackground(new java.awt.Color(255, 0, 0));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Log out");
        jButton22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton22.setBorderPainted(false);
        jButton22.setFocusPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        unitComboBox.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        unitComboBox.setForeground(new java.awt.Color(255, 255, 255));
        unitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Units", "Horticulture", "Cafeteria", "Maintenance", "Security", "Facility" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 329, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22))
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Staff Management", jPanel8);

        jPanel6.setBackground(new java.awt.Color(30, 30, 47));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Roster Logs");

        jScrollPane6.setBorder(null);
        jScrollPane6.setToolTipText("");

        jTableRosters.setBackground(new java.awt.Color(255, 255, 255));
        jTableRosters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Staff ID", "Name", "Unit", "Shift_type", "Start Time", "End Time"
            }
        ));
        jTableRosters.setShowGrid(true);
        jScrollPane6.setViewportView(jTableRosters);

        jScrollPane3.setViewportView(jScrollPane6);

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("Log out");
        jButton18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton18.setBorderPainted(false);
        jButton18.setFocusPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        filterDate.setForeground(new java.awt.Color(255, 255, 255));

        filterCombo.setForeground(new java.awt.Color(255, 255, 255));
        filterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Unit", "Staff ID", "Date" }));
        filterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterComboActionPerformed(evt);
            }
        });

        btnApplyFilter.setBackground(new java.awt.Color(74, 144, 226));
        btnApplyFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApplyFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyFilter.setText("Filter");
        btnApplyFilter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApplyFilter.setBorderPainted(false);
        btnApplyFilter.setFocusPainted(false);
        btnApplyFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyFilterActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(74, 144, 226));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh ");
        btnRefresh.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.setBorderPainted(false);
        btnRefresh.setFocusPainted(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        filterText.setBackground(new java.awt.Color(255, 255, 255));
        filterText.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        filterText.setForeground(new java.awt.Color(0, 0, 0));
        filterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTextActionPerformed(evt);
            }
        });

        rosterUnitComboBox.setForeground(new java.awt.Color(255, 255, 255));
        rosterUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rosterUnitComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosterUnitComboBoxActionPerformed(evt);
            }
        });

        btnRefresh1.setBackground(new java.awt.Color(74, 144, 226));
        btnRefresh1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("Download Current View as CSV");
        btnRefresh1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh1.setBorderPainted(false);
        btnRefresh1.setFocusPainted(false);
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 171, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(filterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(filterDate, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(rosterUnitComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnApplyFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18))
                .addGap(16, 16, 16)
                .addComponent(rosterUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApplyFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Roster Summary", jPanel6);

        jPanel5.setBackground(new java.awt.Color(30, 30, 47));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btnApplyLogFilter.setBackground(new java.awt.Color(74, 144, 226));
        btnApplyLogFilter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApplyLogFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyLogFilter.setText("Filter");
        btnApplyLogFilter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApplyLogFilter.setBorderPainted(false);
        btnApplyLogFilter.setFocusPainted(false);
        btnApplyLogFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyLogFilterActionPerformed(evt);
            }
        });

        jScrollPane5.setBorder(null);
        jScrollPane5.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setToolTipText("");

        logsTable.setBackground(new java.awt.Color(255, 255, 255));
        logsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Log ID", "Staff ID", "Log Date", "Sign-in Time", "Sign-out Time", "Status", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        logsTable.setShowGrid(true);
        jScrollPane5.setViewportView(logsTable);

        jButton17.setBackground(new java.awt.Color(255, 0, 0));
        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Log out");
        jButton17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton17.setBorderPainted(false);
        jButton17.setFocusPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        logFilterCombo.setForeground(new java.awt.Color(255, 255, 255));
        logFilterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        logFilterText.setBackground(new java.awt.Color(255, 255, 255));
        logFilterText.setForeground(new java.awt.Color(0, 0, 0));
        logFilterText.setText("logfiltertext");
        logFilterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logFilterTextActionPerformed(evt);
            }
        });

        logUnitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        logUnitComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logUnitComboBoxActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(74, 144, 226));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Downoald current View as CSV");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setBorderPainted(false);
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Filter By");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logUnitComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logFilterText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logFilterDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(514, 514, 514)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnApplyLogFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton17)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnApplyLogFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logFilterText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logUnitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logFilterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Attendance Logs", jPanel5);

        jPanel7.setBackground(new java.awt.Color(30, 30, 47));

        jButton38.setBackground(new java.awt.Color(74, 144, 226));
        jButton38.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("Reset Password");
        jButton38.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton38.setBorderPainted(false);
        jButton38.setFocusPainted(false);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reset Password", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:Find Staff
        searchStaff();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        // TODO add your handling code here:Filter Button
        filterStaff();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void filterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterComboActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_filterComboActionPerformed

    private void btnApplyFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyFilterActionPerformed
        // TODO add your handling code here:
        applyRosterFilter();
    }//GEN-LAST:event_btnApplyFilterActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadRosterData();
        filterText.setText("");
        filterDate.setDate(null);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void filterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTextActionPerformed

    private void rosterUnitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosterUnitComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rosterUnitComboBoxActionPerformed

    private void logFilterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFilterTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logFilterTextActionPerformed

    private void btnApplyLogFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyLogFilterActionPerformed
        // TODO add your handling code here:
        applyLogFilter();
    }//GEN-LAST:event_btnApplyLogFilterActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        downloadLogsAsCSV();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void logUnitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logUnitComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logUnitComboBoxActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        downloadRosterAsCSV();
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        Login loginform = new Login();
        loginform.setVisible(true);
        loginform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        ResetPassword resetpage = new ResetPassword();
        resetpage.setVisible(true);
        resetpage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton38ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void downloadRosterAsCSV() {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save Roster As");
    fileChooser.setSelectedFile(new java.io.File("roster.csv")); // default filename

    int userSelection = fileChooser.showSaveDialog(this); // `this` = your JFrame

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();

        // Ensure .csv extension
        String filePath = fileToSave.getAbsolutePath();
        if (!filePath.toLowerCase().endsWith(".csv")) {
            fileToSave = new java.io.File(filePath + ".csv");
        }

        try (FileWriter fw = new FileWriter(fileToSave)) {
            DefaultTableModel model = (DefaultTableModel) jTableRosters.getModel();

            // Write headers
            for (int i = 0; i < model.getColumnCount(); i++) {
                fw.write(model.getColumnName(i));
                if (i < model.getColumnCount() - 1) fw.write(",");
            }
            fw.write("\n");

            // Write data rows
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    fw.write(model.getValueAt(i, j).toString());
                    if (j < model.getColumnCount() - 1) fw.write(",");
                }
                fw.write("\n");
            }

            JOptionPane.showMessageDialog(this, "Roster CSV saved to: " + fileToSave.getAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving CSV: " + e.getMessage());
        }
    }
}

   private void downloadLogsAsCSV() {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save Attendance Logs As");
    fileChooser.setSelectedFile(new java.io.File("attendance_logs.csv")); // default filename

    int userSelection = fileChooser.showSaveDialog(this); // `this` = your JFrame

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();

        // Ensure .csv extension
        String filePath = fileToSave.getAbsolutePath();
        if (!filePath.toLowerCase().endsWith(".csv")) {
            fileToSave = new java.io.File(filePath + ".csv");
        }

        try (FileWriter fw = new FileWriter(fileToSave)) {
            DefaultTableModel model = (DefaultTableModel) logsTable.getModel();

            // Write headers
            for (int i = 0; i < model.getColumnCount(); i++) {
                fw.write(model.getColumnName(i));
                if (i < model.getColumnCount() - 1) fw.write(",");
            }
            fw.write("\n");

            // Write data rows
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    fw.write(model.getValueAt(i, j).toString());
                    if (j < model.getColumnCount() - 1) fw.write(",");
                }
                fw.write("\n");
            }

            JOptionPane.showMessageDialog(this, "CSV saved to: " + fileToSave.getAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving CSV: " + e.getMessage());
        }
    }
}

    private void populateRosterUnitComboBox() {
        rosterUnitComboBox.removeAllItems();
        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema",
                "root", "Adesokan2310*"); PreparedStatement ps = con.prepareStatement("SELECT DISTINCT unit FROM shifts"); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                rosterUnitComboBox.addItem(rs.getString("unit"));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void populateUnitsCombo() {
        logUnitComboBox.removeAllItems();
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement("SELECT DISTINCT unit FROM attendance_logs");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                logUnitComboBox.addItem(rs.getString("unit"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void applyLogFilter() {
        String selected = (String) logFilterCombo.getSelectedItem();
        String sql = "SELECT * FROM attendance_logs";
        boolean hasWhere = false;

        if ("By Staff ID".equals(selected)) {
            sql += " WHERE staff_id = ?";
            hasWhere = true;
        } else if ("By Date".equals(selected)) {
            sql += " WHERE log_date = ?";
            hasWhere = true;
        } else if ("By Unit".equals(selected)) {
            sql += " WHERE unit = ?";
            hasWhere = true;
        }

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement(sql);

            if ("By Staff ID".equals(selected)) {
                ps.setInt(1, Integer.parseInt(logFilterText.getText()));
            } else if ("By Date".equals(selected)) {
                java.util.Date date = logFilterDate.getDate();
                ps.setDate(1, new java.sql.Date(date.getTime()));
            } else if ("By Unit".equals(selected)) {
                ps.setString(1, (String) logUnitComboBox.getSelectedItem());
            }

            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) logsTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("log_id"),
                    rs.getInt("staff_id"),
                    rs.getDate("log_date"),
                    rs.getTime("sign_in_time"),
                    rs.getTime("sign_out_time"),
                    rs.getString("status"),
                    rs.getString("unit")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadAttendanceLogs() {
        DefaultTableModel model = (DefaultTableModel) logsTable.getModel();
        model.setRowCount(0); // clear

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM attendance_logs");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("log_id"),
                    rs.getInt("staff_id"),
                    rs.getDate("log_date"),
                    rs.getTime("sign_in_time"),
                    rs.getTime("sign_out_time"),
                    rs.getString("status"),
                    rs.getString("unit")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadRosterData() {
        DefaultTableModel model = (DefaultTableModel) jTableRosters.getModel();
        model.setRowCount(0); // Clear existing rows

        String query = "SELECT sr.shift_date, u.staff_id, u.name, u.unit, s.shift_type, s.start_time, s.end_time "
                + "FROM staff_rosters sr "
                + "JOIN users_tb u ON sr.staff_id = u.staff_id "
                + "JOIN shifts s ON sr.shift_id = s.shift_id";

        try (Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema",
                "root", "Adesokan2310*"); PreparedStatement ps = con.prepareStatement(query); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getDate("shift_date"),
                    rs.getInt("staff_id"),
                    rs.getString("name"),
                    rs.getString("unit"),
                    rs.getString("shift_type"),
                    rs.getTime("start_time"),
                    rs.getTime("end_time")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading roster data: " + e.getMessage());
        }
    }

   private void applyRosterFilter() {
    DefaultTableModel model = (DefaultTableModel) jTableRosters.getModel();
    model.setRowCount(0); // Clear existing rows

    String baseQuery = "SELECT sr.shift_date, u.staff_id, u.name, u.unit, s.shift_type, s.start_time, s.end_time "
                     + "FROM staff_rosters sr "
                     + "JOIN users_tb u ON sr.staff_id = u.staff_id "
                     + "JOIN shifts s ON sr.shift_id = s.shift_id WHERE 1=1";

    List<Object> parameters = new ArrayList<>();

    // Build query dynamically
    if (!filterText.getText().trim().isEmpty()) {
        baseQuery += " AND u.staff_id = ?";
        parameters.add(Integer.parseInt(filterText.getText().trim()));
    }

    if (filterDate.getDate() != null) {
        baseQuery += " AND sr.shift_date = ?";
        parameters.add(new java.sql.Date(filterDate.getDate().getTime()));
    }

    if (rosterUnitComboBox.getSelectedItem() != null && !"All Units".equals(unitComboBox.getSelectedItem())) {
        baseQuery += " AND u.unit = ?";
        parameters.add(rosterUnitComboBox.getSelectedItem().toString());
    }

    // Connect to DB and apply filters
    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema",
            "root", "Adesokan2310*")) {

        PreparedStatement ps = con.prepareStatement(baseQuery);

        // Bind parameters
        for (int i = 0; i < parameters.size(); i++) {
            ps.setObject(i + 1, parameters.get(i));
        }

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getDate("shift_date"),
                rs.getInt("staff_id"),
                rs.getString("name"),
                rs.getString("unit"),
                rs.getString("shift_type"),
                rs.getTime("start_time"),
                rs.getTime("end_time")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error applying filters: " + e.getMessage());
    }
}


    private void loadUnits() {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement("SELECT DISTINCT unit FROM users_tb");
            ResultSet rs = ps.executeQuery();

            unitComboBox.addItem("All Units");
            while (rs.next()) {
                unitComboBox.addItem(rs.getString("unit"));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void searchStaff() {
        String search = searchTextField.getText().trim();
        String unit = unitComboBox.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0); // Clear table

        String sql = "SELECT staff_id, name, email, gender, unit, role, phone_number FROM users_tb WHERE 1=1";
        if (!search.isEmpty()) {
            sql += " AND name LIKE ?";
        }
        if (!unit.equals("All Units")) {
            sql += " AND unit = ?";
        }

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement(sql);

            int index = 1;
            if (!search.isEmpty()) {
                ps.setString(index++, "%" + search + "%");
            }
            if (!unit.equals("All Units")) {
                ps.setString(index, unit);
            }

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("staff_id"),
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("gender"),
                    rs.getString("unit"),
                    rs.getString("role"),
                    rs.getString("phone_number")
                });
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading staff data.");
        }
    }

    private void filterStaff() {
        String searchText = searchTextField.getText().trim();
        String selectedUnit = unitComboBox.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0); // Clear table

        String sql = "SELECT staff_id, name, email, gender, unit, role, phone_number FROM users_tb WHERE 1=1";
        if (!searchText.isEmpty()) {
            sql += " AND name LIKE ?";
        }
        if (!selectedUnit.equals("All Units")) {
            sql += " AND unit = ?";
        }

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement(sql);

            int paramIndex = 1;
            if (!searchText.isEmpty()) {
                ps.setString(paramIndex++, "%" + searchText + "%");
            }
            if (!selectedUnit.equals("All Units")) {
                ps.setString(paramIndex, selectedUnit);
            }

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("staff_id"),
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("gender"),
                    rs.getString("unit"),
                    rs.getString("role"),
                    rs.getString("phone_number")
                });
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error filtering staff data.");
        }
    }

    private void loadAllStaff() {
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0); // Clear previous rows

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
            PreparedStatement ps = con.prepareStatement("SELECT staff_id, name, email, gender, unit, role, phone_number FROM users_tb");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("staff_id"),
                    rs.getString("name"),
                    rs.getString("email"),
                    rs.getString("gender"),
                    rs.getString("unit"),
                    rs.getString("role"),
                    rs.getString("phone_number")
                });
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading staff data.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

  private void loadUnitsToComboBox() {
    try (Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", 
            "root", "Adesokan2310*")) {

        PreparedStatement ps = con.prepareStatement("SELECT DISTINCT TRIM(unit) as unit FROM users_tb");
        ResultSet rs = ps.executeQuery();

        unitComboBox.removeAllItems(); // clean slate
        unitComboBox.addItem("All Units");

        while (rs.next()) {
            String unit = rs.getString("unit");
            if (unit != null && !unit.trim().isEmpty()) {
                unitComboBox.addItem(unit);
            }
        }

        unitComboBox.setSelectedItem("All Units");

        System.out.println("Units loaded."); // debug

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading units: " + ex.getMessage());
    }
}


    private void loadDashboardStats() {
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {

            // Total Staff
            PreparedStatement ps1 = con.prepareStatement("SELECT COUNT(*) FROM users_tb");
            ResultSet rs1 = ps1.executeQuery();
            if (rs1.next()) {
                jLabelTotalStaff.setText(rs1.getString(1));
            }

            // Total Units
            PreparedStatement ps2 = con.prepareStatement("SELECT COUNT(DISTINCT unit) FROM users_tb");
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next()) {
                jLabelTotalUnits.setText(rs2.getString(1));
            }

            // Average Attendance Rate
            PreparedStatement ps3 = con.prepareStatement(
                    "SELECT ROUND((COUNT(*) / (SELECT COUNT(*) FROM attendance_logs)) * 100, 1) AS attendance_rate FROM attendance_logs WHERE status = 'present'"
            );
            ResultSet rs3 = ps3.executeQuery();
            if (rs3.next()) {
                jLabelAttendanceRate.setText(rs3.getString("attendance_rate") + "%");
            }

            // Shift Swaps This Week
            PreparedStatement ps4 = con.prepareStatement(
                    "SELECT COUNT(*) FROM shift_swap_requests WHERE WEEK(request_time) = WEEK(CURDATE())"
            );
            ResultSet rs4 = ps4.executeQuery();
            if (rs4.next()) {
                jLabelShiftSwaps.setText(rs4.getString(1));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectorofServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectorofServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectorofServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectorofServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectorofServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyFilter;
    private javax.swing.JButton btnApplyLogFilter;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton filterButton;
    private javax.swing.JComboBox<String> filterCombo;
    private com.toedter.calendar.JDateChooser filterDate;
    private javax.swing.JTextField filterText;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton38;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAttendanceRate;
    private javax.swing.JLabel jLabelAttendanceRateText;
    private javax.swing.JLabel jLabelShiftSwaps;
    private javax.swing.JLabel jLabelShiftSwapsText;
    private javax.swing.JLabel jLabelTotalStaff;
    private javax.swing.JLabel jLabelTotalStaffText;
    private javax.swing.JLabel jLabelTotalUnits;
    private javax.swing.JLabel jLabelTotalUnitsText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTableRosters;
    private javax.swing.JComboBox<String> logFilterCombo;
    private com.toedter.calendar.JDateChooser logFilterDate;
    private javax.swing.JTextField logFilterText;
    private javax.swing.JComboBox<String> logUnitComboBox;
    private javax.swing.JTable logsTable;
    private javax.swing.JComboBox<String> rosterUnitComboBox;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> unitComboBox;
    // End of variables declaration//GEN-END:variables
}
