/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saasms;

// DigitalPersona SDK Imports
import com.digitalpersona.onetouch.*;
import com.digitalpersona.onetouch.capture.*;
import com.digitalpersona.onetouch.capture.event.*;
import com.digitalpersona.onetouch.processing.*;
import com.digitalpersona.onetouch.verification.*;

// Java Imports
import java.awt.Image;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author adisa
 */
public class FingerprintSignin extends javax.swing.JFrame {
private DPFPCapture capturer;
private DPFPVerification verifier;
private DPFPFeatureSet features;
private DPFPTemplate referenceTemplate;
private long lastScanTime = 0;
private final int COOLDOWN_SECONDS = 10;

    /**
     * Creates new form FingerprintSignin
     */
    public FingerprintSignin() {
        initComponents();
        capturer = DPFPGlobal.getCaptureFactory().createCapture();
verifier = DPFPGlobal.getVerificationFactory().createVerification();

setupCaptureEvents();
capturer.startCapture();
statusLabel.setText("Scanner ready. Place your finger.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        fingerprintLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 47));

        mainPanel.setBackground(new java.awt.Color(30, 30, 47));

        fingerprintLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fingerprintLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("to show staff name");

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Shows sign-in or sign-out status ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Unit", "Status", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fingerprintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fingerprintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void setupCaptureEvents() {
    capturer.addDataListener(new DPFPDataAdapter() {
        @Override
        public void dataAcquired(DPFPDataEvent e) {
            DPFPSample sample = e.getSample();
            processSample(sample);
        }
    });

    capturer.addReaderStatusListener(new DPFPReaderStatusAdapter() {
        public void readerConnected(DPFPReaderStatusEvent e) {
            statusLabel.setText("Scanner connected.");
        }

        public void readerDisconnected(DPFPReaderStatusEvent e) {
            statusLabel.setText("Scanner disconnected.");
        }
    });
}
    private void restartScanner() {
    try {
        capturer.stopCapture();  // Stop current scanning session
        capturer.startCapture(); // Start a new scanning session
        statusLabel.setText("Scanner ready. Place your finger.");
    } catch (Exception e) {
        statusLabel.setText("Error restarting scanner.");
        e.printStackTrace();
    }
}

private void processSample(DPFPSample sample) {
    displayFingerprintImage(sample);
    
    if (System.currentTimeMillis() - lastScanTime < COOLDOWN_SECONDS * 1000) {
        statusLabel.setText("Please wait before scanning again...");
        restartScanner();
        return;
    }
    lastScanTime = System.currentTimeMillis();

    try {
        features = DPFPGlobal.getFeatureExtractionFactory()
            .createFeatureExtraction().createFeatureSet(sample, DPFPDataPurpose.DATA_PURPOSE_VERIFICATION);
    } catch (DPFPImageQualityException ex) {
        statusLabel.setText("Poor fingerprint quality.");
        restartScanner();
        return;
    }

    if (features == null) {
        statusLabel.setText("Could not extract fingerprint features.");
        restartScanner();
        return;
    }

    matchAgainstDatabase();
}

private void matchAgainstDatabase() {
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {

        PreparedStatement ps = con.prepareStatement("SELECT staff_id, name, unit, email, fingerprint_template FROM users_tb");
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            byte[] data = rs.getBytes("fingerprint_template");
            if (data == null) continue;

            referenceTemplate = DPFPGlobal.getTemplateFactory().createTemplate();
            referenceTemplate.deserialize(data);

            if (verifier.verify(features, referenceTemplate).isVerified()) {
                int staffId = rs.getInt("staff_id");
                String name = rs.getString("name");
                String unit = rs.getString("unit");
                String email = rs.getString("email");

                nameLabel.setText(name);

                // Pass email to logAttendance
                logAttendance(staffId, name, unit);
                return;
            }
        }

        statusLabel.setText("Fingerprint not recognized.");
        nameLabel.setText("");

    } catch (Exception e) {
        statusLabel.setText("Error: " + e.getMessage());
        e.printStackTrace();
    }
}
private String getStaffEmailById(int staffId) {
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
        PreparedStatement ps = con.prepareStatement("SELECT email FROM users_tb WHERE staff_id = ?");
        ps.setInt(1, staffId);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) return rs.getString("email");
    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}

private void logAttendance(int staffId, String name, String unit) {
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {

        LocalDate today = LocalDate.now();
        LocalTime now = LocalTime.now();
        String shiftType = null;
        String status;

        if (!unit.equalsIgnoreCase("Horticulture")) {
            PreparedStatement ps = con.prepareStatement("""
                SELECT s.shift_type, s.start_time, s.end_time 
                FROM staff_rosters sr 
                JOIN shifts s ON sr.shift_id = s.shift_id 
                WHERE sr.staff_id = ? AND sr.shift_date = ?
            """);
            ps.setInt(1, staffId);
            ps.setDate(2, Date.valueOf(today));
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) {
                statusLabel.setText("No shift assigned today.");
                return;
            }

            shiftType = rs.getString("shift_type");
            LocalTime start = rs.getTime("start_time").toLocalTime();
            LocalTime end = rs.getTime("end_time").toLocalTime();
            boolean isOvernight = end.isBefore(start);

            PreparedStatement check = con.prepareStatement("""
                SELECT * FROM attendance_logs 
                WHERE staff_id = ? AND log_date = ? AND shift_type = ? AND sign_out_time IS NULL
            """);
            check.setInt(1, staffId);
            check.setDate(2, Date.valueOf(today));
            check.setString(3, shiftType);
            ResultSet log = check.executeQuery();

            if (log.next()) {
                status = !isOvernight && now.isBefore(end) ? "Early Sign-out" : "Signed Out";

                PreparedStatement out = con.prepareStatement("""
                    UPDATE attendance_logs SET sign_out_time = ?, status = ? WHERE log_id = ?
                """);
                out.setTime(1, Time.valueOf(now));
                out.setString(2, status);
                out.setInt(3, log.getInt("log_id"));
                out.executeUpdate();
            } else {
                status = !isOvernight && now.isAfter(start.plusMinutes(15)) ? "Late Sign-in" : "Signed In";

                PreparedStatement in = con.prepareStatement("""
                    INSERT INTO attendance_logs (staff_id, log_date, sign_in_time, status, unit, shift_type)
                    VALUES (?, ?, ?, ?, ?, ?)
                """);
                in.setInt(1, staffId);
                in.setDate(2, Date.valueOf(today));
                in.setTime(3, Time.valueOf(now));
                in.setString(4, status);
                in.setString(5, unit);
                in.setString(6, shiftType);
                in.executeUpdate();
            }
        } else {
            PreparedStatement check = con.prepareStatement("""
                SELECT * FROM attendance_logs WHERE staff_id = ? AND log_date = ? AND shift_type IS NULL AND sign_out_time IS NULL
            """);
            check.setInt(1, staffId);
            check.setDate(2, Date.valueOf(today));
            ResultSet log = check.executeQuery();

            if (log.next()) {
                status = "Signed Out";
                PreparedStatement out = con.prepareStatement("""
                    UPDATE attendance_logs SET sign_out_time = ?, status = ? WHERE log_id = ?
                """);
                out.setTime(1, Time.valueOf(now));
                out.setString(2, status);
                out.setInt(3, log.getInt("log_id"));
                out.executeUpdate();
            } else {
                status = "Signed In";
                PreparedStatement in = con.prepareStatement("""
                    INSERT INTO attendance_logs (staff_id, log_date, sign_in_time, status, unit)
                    VALUES (?, ?, ?, ?, ?)
                """);
                in.setInt(1, staffId);
                in.setDate(2, Date.valueOf(today));
                in.setTime(3, Time.valueOf(now));
                in.setString(4, status);
                in.setString(5, unit);
                in.executeUpdate();
            }
        }

        // ✅ Show success message
        statusLabel.setText(status + " at " + now);

        // ✅ Add to JTable on top
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.insertRow(0, new Object[]{name, unit, status, now.toString()});

        // ✅ Send email asynchronously
        new Thread(() -> {
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/staffattendanceandshiftmanagementschema", "root", "Adesokan2310*")) {
                PreparedStatement ps = conn.prepareStatement("SELECT email FROM users_tb WHERE staff_id = ?");
                ps.setInt(1, staffId);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String email = rs.getString("email");
                    String message = """
                        Dear %s,

                        This is to confirm your %s on %s at %s.
                        Unit: %s

                        If you did not perform this action, please report immediately.

                        Regards,
                        PAUSAAMS System
                    """.formatted(name, status, today.toString(), now.toString(), unit);

                    EmailSender.sendSimpleEmail(email, "Attendance Confirmation - " + status, message);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }).start();

    } catch (Exception e) {
        statusLabel.setText("DB Error: " + e.getMessage());
    }
}



private void displayFingerprintImage(DPFPSample sample) {
    Image image = DPFPGlobal.getSampleConversionFactory().createImage(sample);
    fingerprintLabel.setIcon(new ImageIcon(
        image.getScaledInstance(fingerprintLabel.getWidth(), fingerprintLabel.getHeight(), Image.SCALE_SMOOTH)
    ));
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FingerprintSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FingerprintSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FingerprintSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FingerprintSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FingerprintSignin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fingerprintLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
